import QRCode from "qrcode";
import { requireStaff } from "@/lib/auth";
import { CAFE } from "@/lib/cafe";
import { listTables } from "@/lib/repositories/tables";
import styles from "./tables.module.css";

export const dynamic = "force-dynamic";

const base = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3001";

/**
 * Printable QR sheet — one card per table.
 *
 * Rendered as inline SVG rather than a PNG: it prints crisply at any size,
 * needs no image hosting, and a code that scans badly is a table that cannot
 * order.
 */
export default async function TablesPage() {
  await requireStaff("MANAGER");
  const tables = await listTables();

  const cards = await Promise.all(
    tables.map(async (table) => {
      const url = `${base}/t/${table.qrToken}`;
      const svg = await QRCode.toString(url, {
        type: "svg",
        errorCorrectionLevel: "M",
        margin: 1,
        // Pure black on white: printers and scanners both prefer it, and a
        // pistachio QR on espresso would look lovely and scan poorly.
        color: { dark: "#000000", light: "#FFFFFF" },
      });
      return { table, url, svg };
    }),
  );

  return (
    <>
      <div className={styles.head}>
        <h1 className={`display ${styles.title}`}>QR codes</h1>
        <p className={styles.muted}>
          One per table. Print, cut, and stand them on the tables — scanning
          opens that table&rsquo;s ordering page.
        </p>
        <p className={styles.warn}>
          Treat these like keys. Anyone holding a code can add to that
          table&rsquo;s bill, so replace a card if it goes missing.
        </p>
      </div>

      <div className={styles.sheet}>
        {cards.map(({ table, url, svg }) => (
          <article key={table.id} className={styles.card}>
            <div className={styles.cardTop}>
              <span className={`display ${styles.cafe}`}>{CAFE.name}</span>
              <span className={styles.tableLabel}>Table {table.label}</span>
            </div>

            <div
              className={styles.qr}
              // Generated by the qrcode library from our own URL — not user input.
              dangerouslySetInnerHTML={{ __html: svg }}
            />

            <p className={styles.instruction}>
              Scan to see the menu and order from your table
            </p>
            <p className={styles.url}>{url}</p>
          </article>
        ))}
      </div>
    </>
  );
}
